services:
  capture-kubeconfig:
    image: ${DESKTOP_PLUGIN_IMAGE}
    network_mode: "host"
    volumes:
      - kubeconfig:/root/.kube:rw
    healthcheck:
      test: curl --unix-socket /run/guest-services/k8s-dd-extension.sock http:/x/y/z | grep "Not Found"
      interval: 1s
      retries: 100
      start_period: 1s
      timeout: 10s

  k9s:
    hostname: k9s
    container_name: k9s
    # Source: https://github.com/spurin/container-k9s-ttyd-kubectl
    # Container: https://hub.docker.com/r/spurin/k9s-ttyd-kubectl
    image: spurin/k9s-ttyd-kubectl
    command: [ "/bin/ttyd", "-p", "35781", "sh",  "-c", "'/bin/k9s; exit 1'" ]
    network_mode: "host"
    volumes:
      - kubeconfig:/kubeconfig
#    ports:
#      - "0.0.0.0:35781:35781"
#      - 35781:7681
    depends_on:
      capture-kubeconfig:
        condition: service_healthy

volumes:
  kubeconfig:
